### ISSUE TITLE
Add tslint

### ISSUE THREAD

**Issue by davidnguyen179** [davidnguyen179/storybook-wdio#2]
To make code convention consistently, It would be better to have `tslint` config to prevent developer mistake.

1. Add `tslint` config file
2. Add `validate` command in `package.json`

**Comment by nartc** [comment]
I would consider `typescript-eslint` instead of `tslint`. Check this blog post from `tslint` author: https://medium.com/palantir/tslint-in-2019-1a144c2317a9 and also this one from `ESLint`: https://eslint.org/blog/2019/01/future-typescript-eslint

**Comment by davidnguyen179** [comment]
Do u think we need the command in "package.json" for this one in order to run lint for the whole project and support git hook in the future?

**Comment by nartc** [comment]
@davidnguyen179 it's been a standard to have `lint` run as a script. Have you looked into `lint-staged`?

**Comment by davidnguyen179** [comment]
yeah heard about it. It would be nice if we have it!

**Comment by davidnguyen179** [comment]
@nartc Done!
