### ISSUE TITLE
Add docker-compose.yml to start chrome & firefox drivers

### ISSUE THREAD

**Issue by davidnguyen179** [davidnguyen179/storybook-wdio#32]
http://allselenium.info/selenium-docker-parallel-execution-made-easy/

**Comment by haoict** [comment]
Let me do this

**Comment by davidnguyen179** [comment]
@haoict  How many stuffs contains in docker-compose.yml?

**Comment by haoict** [comment]
Done:
https://github.com/davidnguyen179/storybook-wdio/pull/44
https://github.com/davidnguyen179/storybook-wdio/pull/45
